name: Latest Blog Post Workflow
on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@fernandoshadowbr" # Replace with your RSS feed URL
